global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # vLLM engine metrics
  - job_name: "vllm-engine"
    static_configs:
      - targets: ["vllm-engine:8000"]
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Router metrics (if enabled)
  - job_name: "vllm-router"
    static_configs:
      - targets: ["vllm-router:8000"]
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s