global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vllm-engine'
    static_configs:
      - targets: ['vllm-engine:8000']
    metrics_path: '/metrics'
    
  - job_name: 'vllm-router'
    static_configs:
      - targets: ['vllm-router:8000']
    metrics_path: '/metrics'